# Generated by Django 2.2 on 2019-07-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='provider',
            field=models.CharField(default='', max_length=20),
        ),
    ]
