# Generated by Django 2.2 on 2019-07-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal_provider', '0002_auto_20190706_0858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.AlterField(
            model_name='currencies',
            name='provider',
            field=models.TextField(default=''),
        ),
    ]
