# Generated by Django 2.2 on 2019-07-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimal_provider', '0003_auto_20190706_1643'),
    ]

    operations = [
        migrations.RenameModel('Currencies', 'ExchangeRate')
    ]
