# Generated by Django 2.2 on 2019-07-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.TextField(default='')),
                ('code', models.CharField(default='usd', max_length=3)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
    ]
